# Generated by Django 5.2.6 on 2025-12-22 07:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_council_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=100)),
                ('experience', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contractor',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2027-01-01'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Started', 'started'), ('Pending', 'pending')], default='pending', max_length=10),
        ),
        migrations.AlterModelTable(
            name='council',
            table='Council',
        ),
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.project')),
            ],
            options={
                'db_table': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Rejected', 'rejected'), ('Approved', 'approved'), ('Pending', 'pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.council')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.project')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.contractor')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.package')),
            ],
            options={
                'db_table': 'Bid',
            },
        ),
    ]
