# Generated by Django 5.2.6 on 2025-12-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_alter_bid_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
