# Generated by Django 5.2.6 on 2026-01-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='contact_email',
            field=models.EmailField(max_length=254, default='admin@example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='contact_email',
            field=models.EmailField(max_length=254, default='admin@example.com'),
            preserve_default=False,
        ),
    ]
