# Generated by Django 5.2.6 on 2026-01-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0010_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='document1',
            field=models.FileField(blank=True, null=True, upload_to='bid_documents/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='bid_documents/'),
        ),
        migrations.AddField(
            model_name='bid',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='bid_documents/'),
        ),
    ]
