# Generated by Django 5.2.6 on 2026-01-10 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0011_bid_document1_bid_document2_bid_document3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('project_created', 'Project Created'), ('package_created', 'Package Created'), ('package_deleted', 'Package Deleted'), ('bid_placed', 'Bid Placed'), ('bid_approved', 'Bid Approved'), ('bid_rejected', 'Bid Rejected'), ('project_ended', 'Project Ended'), ('project_deleted', 'Project Deleted'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.bid')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.package')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_chain.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'Activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
